### ISSUE TITLE
Docker Deployment Documentation

### ISSUE THREAD

**Issue by almereyda** [peerlibrary/peerlibrary#711]
I've first tried to build the `Dockerfile` and link it to a MongoDB, but that didn't work.

Then I discovered `run.sh`, but it also has no documentation on how to be used. Maybe a `fig.yml` could spare some headaches here?

I.e., `docker run --name mongodb -d mongo` is necessary to run beforehand, but not documented.
Also none of the containers of `run.sh` exposes any ports like `-p 3000:3000`.

Would you mind updating the docs for easier redeployability?

Additionally it could make sense to move the files to another directory than `/srv`, or a data volume-only container, as one may be running docker from an unelevated user that has no writing rights there. Also SELinux would regularly fire, if present.

**Comment by almereyda** [comment]
@mitar Do you have any updates on this; esp. how to use `run.sh`?

See also

* https://github.com/peerlibrary/peerlibrary/blame/development/Dockerfile
* https://github.com/peerlibrary/peerlibrary/blame/development/run.sh

**Comment by mitar** [comment]
I updated Dockerfile and documented inside run.sh what is expected of things to configure.
