### ISSUE TITLE
You don't have the XCode Developer Tools.

### ISSUE THREAD

**Issue by dipenpatel235** [peerlibrary/peerlibrary#717]
Hello i getting XCode Developer tool error.
So this installation is only applicable for mac pc/server ?

it is not usable in centos 7 server ?

Error:
X11 is not in /usr/X11.
You don't have the XCode Developer Tools.
Note after you download and install XCode, you still need to download the Developer Tools.
You need to type export PKG_CONFIG_PATH=/opt/X11/lib/pkgconfig.

**Comment by mitar** [comment]
No. `checkdependencies.s` is just a helpful script to help you run on Mac OS X. See readme.
